# Generated by org.mangosdk.spi.processor.SpiProcessor (0.2.4)
# Sat, 9 Jul 2016 11:06:31 +0400
"thresholdLevel = " + thresholdLevel + ", id = " + getId() + ", name = " +
*
* (non-Javadoc)
* ----------------------------------------------------------------------------
* 1. The University of Tuebingen, Germany
* 2. EMBL European Bioinformatics Institute (EBML-EBI), Hinxton, UK
* 3. The California Institute of Technology, Pasadena, CA, USA
* 4. The University of California, San Diego, La Jolla, CA, USA
* 5. The Babraham Institute, Cambridge, UK
* @author Deviser
* @date $Date: $
* @param id
* @param level
* @param name
* @param orig the Input instance to copy.
* @param qualitativeSpecies
* @param sign
* @param thresholdLevel
* @param transitionEffect
* @param version
* @return
* @return false
* @return the qualitativeSpecies
* @return the sign
* @return the thresholdLevel
* @return the transitionEffect
* @return true
* @return {@code true} if the unset of the qualitativeSpecies attribute was
* @return {@code true} if the unset of the sign attribute was successful
* @return {@code true} if the unset of the thresholdLevel attribute was
* @return {@code true} if the unset of the transitionEffect attribute was
* @see org.sbml.jsbml.NamedSBase
* @since 1.2
* @version $Rev: 2465 $
* Copyright (C) 2009-2016 jointly by the following organizations:
* Generated serial version identifier.
* This file is part of JSBML. Please visit <http://sbml.org/Software/JSBML>
* This library is free software; you can redistribute it and/or modify it
* and also available online as <http://sbml.org/Software/JSBML/License>.
* for the latest version of JSBML and more information about SBML.
* in the file named "LICENSE.txt" included with this software distribution
* see java.lang.Object
* successful
* the Free Software Foundation. A copy of the license agreement is provided
* under the terms of the GNU Lesser General Public License as published b
*/
/*
/* (non-Javadoc)
/* Assignment operator for Input.
/* hashcode method for Input.
/**
@Override
Input obj = (Input) object;
Integer oldThresholdLevel = this.thresholdLevel;
Integer oldThresholdLevel = thresholdLevel;
Model model = getModel();
String oldQualitativeSpecies = this.qualitativeSpecies;
boolean equals = super.equals(object);
boolean isAttributeRead = super.readAttribute(attributeName, prefix, value);
equals &= (obj.getQualitativeSpecies() == getQualitativeSpecies());
equals &= (obj.getSign() == getSign());
equals &= (obj.getThresholdLevel() == getThresholdLevel());
equals &= (obj.getTransitionEffect() == getTransitionEffect());
equals &= obj.isSetQualitativeSpecies() == isSetQualitativeSpecies();
equals &= obj.isSetSign() == isSetSign();
equals &= obj.isSetThresholdLevel() == isSetThresholdLevel();
equals &= obj.isSetTransitionEffect() == isSetTransitionEffect();
final int prime = 4718249;
firePropertyChange(QualConstants.qualitativeSpecies,
firePropertyChange(QualConstants.thresholdLevel, oldThresholdLevel,
getName() + "]";
hashCode += prime * getQualitativeSpecies().hashCode();
hashCode += prime * getThresholdLevel();
hashCode += prime;
if (!isAttributeRead) {
if ((qualitativeSpecies == null) || (qualitativeSpecies.isEmpty())) {
if (Sign_isValid(sign) == 0) {
if (TransitionInputEffect_isValid(transitionEffect) == 0) {
if (attributeName.equals(QualConstants.sign)) {
if (equals && isSetQualitativeSpecies()) {
if (equals && isSetSign()) {
if (equals && isSetThresholdLevel()) {
if (equals && isSetTransitionEffect()) {
if (equals) {
if (getLevelAndVersion().compareTo(Integer.valueOf(3), Integer.valueOf(1)) < 0) {
if (isSetQualitativeSpecies()) {
if (isSetSign()) {
if (isSetThresholdLevel()) {
if (isSetTransitionEffect()) {
if (model != null) {
if (orig.isSetQualitativeSpecies()) {
if (orig.isSetSign()) {
if (orig.isSetThresholdLevel()) {
if (orig.isSetTransitionEffect()) {
if (qualitativeSpecies != this.qualitativeSpecies) {
import java.util.Map;
import org.sbml.jsbml.*;
import org.sbml.jsbml.util.*;
import org.sbml.jsbml.util.filters.*;
initDefaults();
int hashCode = super.hashCode();
isAttributeRead = false;
isAttributeRead = true;
oldQualitativeSpecies, this.qualitativeSpecies);
package org.sbml.jsbml.ext.qual;
packageName = QualConstants.shortLabel;
private Integer thresholdLevel;
private Sign sign;
private String qualitativeSpecies;
private TransitionInputEffect transitionEffect;
private static final long serialVersionUID = 62245043425750560L;
public Input clone() {
public Input() {
public Input(Input orig) {
public Input(String id) {
public Input(String id, String name, int level, int version) {
public Input(String id, int level, int version) {
public Input(int level, int version) {
public QualitativeSpecies getQualitativeSpeciesInstance() {
public Sign getSign() {
public String getQualitativeSpecies() {
public String toString() {
public TransitionInputEffect getTransitionEffect() {
public boolean equals(Object object) {
public boolean isIdMandatory() {
public boolean isQualitativeSpeciesMandatory() {
public boolean isSetQualitativeSpecies() {
public boolean isSetQualitativeSpeciesInstance() {
public boolean isSetSign() {
public boolean isSetThresholdLevel() {
public boolean isSetTransitionEffect() {
public boolean isSignMandatory() {
public boolean isThresholdLevelMandatory() {
public boolean isTransitionEffectMandatory() {
public boolean readAttribute(String attributeName, String prefix, String value) {
public boolean setQualitativeSpecies(String qualitativeSpecies) {
public boolean unsetQualitativeSpecies() {
public boolean unsetSign() {
public boolean unsetThresholdLevel() {
public boolean unsetTransitionEffect() {
public class Input extends AbstractNamedSBase implements UniqueNamedSBase, CallableSBase {
public int getThresholdLevel() {
public int hashCode() {
public void initDefaults() {
public void setSign(Sign sign) {
public void setThresholdLevel(int thresholdLevel) {
public void setTransitionEffect(TransitionInputEffect transitionEffect) {
qualitativeSpecies + ", transitionEffect = " + transitionEffect + ", "
qualitativeSpecies = null;
return "Input [sign = " + sign + ", qualitativeSpecies = " +
return (sign != SIGN_INVALID);
return (transitionEffect != TRANSITION_INPUT_EFFECT_INVALID);
return LIBSBML_INVALID_ATTRIBUTE_VALUE;
return LIBSBML_OPERATION_SUCCESS;
return equals;
return false;
return getQualitativeSpeciesInstance() != null;
return hashCode;
return isAttributeRead;
return isSetQualitativeSpecies() ? qualitativeSpecies : "";
return model.getQualitativeSpecies(getQualitativeSpecies());
return new Input(this);
return null;
return qualitativeSpecies != null;
return setQualitativeSpecies((String) null);
return sign;
return thresholdLevel != null;
return thresholdLevel.intValue();
return transitionEffect;
return true;
setPackageVersion(-1);
setQualitativeSpecies(orig.getQualitativeSpecies());
setQualitativeSpecies(value);
setSign(StringTools.parseSBMLSign(value));
setSign(orig.getSign());
setThresholdLevel(StringTools.parseSBMLInt(value));
setThresholdLevel(orig.getThresholdLevel());
setTransitionEffect(StringTools.parseSBMLTransitionInputEffect(value));
setTransitionEffect(orig.getTransitionEffect());
sign = SIGN_INVALID;
sign = null;
sign = sign;
super();
super(id);
super(id, name, level, version);
super(orig);
this(id, null, level, version);
this(null, null, level, version);
this.qualitativeSpecies = null;
this.qualitativeSpecies = qualitativeSpecies;
this.thresholdLevel = thresholdLevel;
this.thresholdLevel);
thresholdLevel = null;
thresholdLevel);
throw new LevelVersionError(getElementName(), level, version);
throw new PropertyUndefinedError(QualConstants.sign, this);
throw new PropertyUndefinedError(QualConstants.thresholdLevel, this);
throw new PropertyUndefinedError(QualConstants.transitionEffect, this);
transitionEffect = TRANSITION_INPUT_EFFECT_INVALID;
transitionEffect = null;
transitionEffect = transitionEffect;
}
}      else if (attributeName.equals(QualConstants.qualitativeSpecies)) {
}      else if (attributeName.equals(QualConstants.thresholdLevel)) {
}      else if (attributeName.equals(QualConstants.transitionEffect)) {
}  }
} else {
