# Generated by org.mangosdk.spi.processor.SpiProcessor (0.2.4)
# Sun, 3 Jul 2016 01:27:03 +0400
*
* ----------------------------------------------------------------------------
* 1. The University of Tuebingen, Germany
* 2. EMBL European Bioinformatics Institute (EBML-EBI), Hinxton, UK
* 3. The California Institute of Technology, Pasadena, CA, USA
* 4. The University of California, San Diego, La Jolla, CA, USA
* 5. The Babraham Institute, Cambridge, UK
* @author Deviser
* @date $Date: $
* @param id
* @param level
* @param name
* @param orig the Output instance to copy.
* @param outputLevel
* @param qualitativeSpecies
* @param transitionEffect
* @param version
* @return
* @return false
* @return the outputLevel
* @return the qualitativeSpecies
* @return the transitionEffect
* @return {@code true} if the unset of the outputLevel attribute was
* @return {@code true} if the unset of the qualitativeSpecies attribute was
* @return {@code true} if the unset of the transitionEffect attribute was
* @see org.sbml.jsbml.NamedSBase
* @since 1.2
* @version $Rev: 2465 $
* Copyright (C) 2009-2016 jointly by the following organizations:
* Generated serial version identifier.
* This file is part of JSBML. Please visit <http://sbml.org/Software/JSBML>
* This library is free software; you can redistribute it and/or modify it
* and also available online as <http://sbml.org/Software/JSBML/License>.
* for the latest version of JSBML and more information about SBML.
* in the file named "LICENSE.txt" included with this software distribution
* successful
* the Free Software Foundation. A copy of the license agreement is provided
* under the terms of the GNU Lesser General Public License as published b
*/
/*
/* (non-Javadoc)
/**
@Override
Integer oldOutputLevel = outputLevel;
Integer oldOutputLevel = this.outputLevel;
Model model = getModel();
String oldQualitativeSpecies = this.qualitativeSpecies;
firePropertyChange(QualConstants.outputLevel, oldOutputLevel,
firePropertyChange(QualConstants.qualitativeSpecies,
if ((qualitativeSpecies == null) || (qualitativeSpecies.isEmpty())) {
if (TransitionOutputEffect_isValid(transitionEffect) == 0) {
if (getLevelAndVersion().compareTo(Integer.valueOf(3), Integer.valueOf(1)) < 0) {
if (isSetOutputLevel()) {
if (isSetQualitativeSpecies()) {
if (isSetTransitionEffect()) {
if (model != null) {
if (orig.isSetOutputLevel()) {
if (orig.isSetQualitativeSpecies()) {
if (orig.isSetTransitionEffect()) {
if (qualitativeSpecies != this.qualitativeSpecies) {
import java.util.Map;
import org.sbml.jsbml.*;
import org.sbml.jsbml.util.*;
import org.sbml.jsbml.util.filters.*;
initDefaults();
oldQualitativeSpecies, this.qualitativeSpecies);
outputLevel = null;
outputLevel);
package org.sbml.jsbml.ext.qual;
packageName = QualConstants.shortLabel;
private Integer outputLevel;
private String qualitativeSpecies;
private TransitionOutputEffect transitionEffect;
private static final long serialVersionUID = -6048861420699176889L;
public Output clone() {
public Output() {
public Output(Output orig) {
public Output(String id) {
public Output(String id, String name, int level, int version) {
public Output(String id, int level, int version) {
public Output(int level, int version) {
public QualitativeSpecies getQualitativeSpeciesInstance() {
public String getQualitativeSpecies() {
public TransitionOutputEffect getTransitionEffect() {
public boolean isIdMandatory() {
public boolean isOutputLevelMandatory() {
public boolean isQualitativeSpeciesMandatory() {
public boolean isSetOutputLevel() {
public boolean isSetQualitativeSpecies() {
public boolean isSetQualitativeSpeciesInstance() {
public boolean isSetTransitionEffect() {
public boolean isTransitionEffectMandatory() {
public boolean setQualitativeSpecies(String qualitativeSpecies) {
public boolean unsetOutputLevel() {
public boolean unsetQualitativeSpecies() {
public boolean unsetTransitionEffect() {
public class Output extends AbstractNamedSBase implements UniqueNamedSBase, CallableSBase {
public int getOutputLevel() {
public void initDefaults() {
public void setOutputLevel(int outputLevel) {
public void setTransitionEffect(TransitionOutputEffect transitionEffect) {
qualitativeSpecies = null;
return (transitionEffect != TRANSITION_OUTPUT_EFFECT_INVALID);
return LIBSBML_INVALID_ATTRIBUTE_VALUE;
return LIBSBML_OPERATION_SUCCESS;
return false;
return getQualitativeSpeciesInstance() != null;
return isSetQualitativeSpecies() ? qualitativeSpecies : "";
return model.getQualitativeSpecies(getQualitativeSpecies());
return new Output(this);
return null;
return outputLevel != null;
return outputLevel.intValue();
return qualitativeSpecies != null;
return setQualitativeSpecies((String) null);
return transitionEffect;
return true;
setOutputLevel(orig.getOutputLevel());
setPackageVersion(-1);
setQualitativeSpecies(orig.getQualitativeSpecies());
setTransitionEffect(orig.getTransitionEffect());
super();
super(id);
super(id, name, level, version);
super(orig);
this(id, null, level, version);
this(null, null, level, version);
this.outputLevel = outputLevel;
this.outputLevel);
this.qualitativeSpecies = null;
this.qualitativeSpecies = qualitativeSpecies;
throw new LevelVersionError(getElementName(), level, version);
throw new PropertyUndefinedError(QualConstants.outputLevel, this);
throw new PropertyUndefinedError(QualConstants.transitionEffect, this);
transitionEffect = TRANSITION_OUTPUT_EFFECT_INVALID;
transitionEffect = null;
transitionEffect = transitionEffect;
}
}  }
} else {
