# Generated by org.mangosdk.spi.processor.SpiProcessor (0.2.4)
# Sat, 25 Jun 2016 13:10:07 +0400
*
* ----------------------------------------------------------------------------
* 1. The University of Tuebingen, Germany
* 2. EMBL European Bioinformatics Institute (EBML-EBI), Hinxton, UK
* 3. The California Institute of Technology, Pasadena, CA, USA
* 4. The University of California, San Diego, La Jolla, CA, USA
* 5. The Babraham Institute, Cambridge, UK
* @author Deviser
* @date $Date: $
* @param id
* @param level
* @param name
* @param version
* @since 1.2
* @version $Rev: 2465 $
* Copyright (C) 2009-2016 jointly by the following organizations:
* Generated serial version identifier.
* This file is part of JSBML. Please visit <http://sbml.org/Software/JSBML>
* This library is free software; you can redistribute it and/or modify it
* and also available online as <http://sbml.org/Software/JSBML/License>.
* for the latest version of JSBML and more information about SBML.
* in the file named "LICENSE.txt" included with this software distribution
* the Free Software Foundation. A copy of the license agreement is provided
* under the terms of the GNU Lesser General Public License as published b
*/
/*
/* (non-Javadoc)
/**
@Override
functionTerm = null;
if (getLevelAndVersion().compareTo(Integer.valueOf(3), Integer.valueOf(1)) < 0) {
import java.text.MessageFormat;
import java.util.Map;
import org.sbml.jsbml.*;
import org.sbml.jsbml.util.*;
import org.sbml.jsbml.util.filters.*;
initDefaults();
input = null;
output = null;
package org.sbml.jsbml.ext.qual;
packageName = QualConstants.shortLabel;
private static final long serialVersionUID = -6048861420699176889L;
public Transition clone() {
public Transition() {
public Transition(String id) {
public Transition(String id, String name, int level, int version) {
public Transition(String id, int level, int version) {
public Transition(int level, int version) {
public boolean isIdMandatory() {
public class Transition extends AbstractNamedSBase implements UniqueNamedSBase {
public void initDefaults() {
return new Transition(this);
return true;
setPackageVersion(-1);
super();
super(id);
super(id, name, level, version);
this(id, null, level, version);
this(null, null, level, version);
throw new LevelVersionError(getElementName(), level, version);
}
